# Generated by Django 3.1.1 on 2020-09-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200912_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='age',
        ),
        migrations.AddField(
            model_name='actor',
            name='year',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Год рождения'),
        ),
    ]
